parent_headers = {
    'ID': '',
    'Type': 'variable',
    'SKU': '', # gen skew function
    'Name': '',# change name function
    'Published': '1',
    'Is featured?': '0',
    'Visibility in catalog': 'visible',
    'Short description': '',
    'Description': '', # gen description
    'Date sale price starts': '',
    'Date sale price ends': '',
    'Tax status': 'taxable',
    'Tax class': '',
    'In stock?': '0',
    'Stock': '0',
    'Low stock amount': '',
    'Backorders allowed?': '0',
    'Sold individually?': '0',
    'Weight (lbs)': '',
    'Length (in)': '',
    'Width (in)': '',
    'Height (in)': '',
    'Allow customer reviews?': '0',
    'Purchase note': '',
    'Sale price': '9000.01',
    'Regular price': '9000.01',
    'Categories': '', # category function
    'Tags': '', # get tag function
    'Shipping class': 'sng-1', 
    'Images': '', # get image function
    'Download limit': '',
    'Download expiry days': '',
    'Parent': '',
    'Grouped products': '',
    'Upsells': '',
    'Cross-sells': '',
    'External URL': '',
    'Button text': '',
    'Position': '0',
    'Minimum Quantity': '',
    'Maximum Quantity': '',
    'Attribute 1 name': 'Condition',
    'Attribute 1 value(s)': 'Near Mint, Lightly Played, Moderately Played, Heavily Played, Damaged',
    'Attribute 1 visible': '1',
    'Attribute 1 global': '1',
    'Attribute 2 name': 'Foil',
    'Attribute 2 value(s)': 'Non Foil, Foil',
    'Attribute 2 visible': '1',
    'Attribute 2 global': '1',
    'Attribute 3 name': 'Rarity',
    'Attribute 3 value(s)': '',
    'Attribute 3 visible': '1',
    'Attribute 3 global': '1',
    'Attribute 4 name': 'Type',
    'Attribute 4 value(s)': '',
    'Attribute 4 visible': '1',
    'Attribute 4 global': '1',
    # 'Attribute 5 name': '',
    # 'Attribute 5 value(s)': '',
    # 'Attribute 5 visible': '1',
    # 'Attribute 5 global': '1',
    # 'Attribute 6 name': '',
    # 'Attribute 6 value(s)': '',
    # 'Attribute 6 visible': '1',
    # 'Attribute 6 global': '1',
}

child_headers = {
    'ID': '',
    'Type': 'variation',
    'SKU': '',
    'Name': '',
    'Published': '1',
    'Is featured?': '0',
    'Visibility in catalog': 'visible',
    'Short description': '',
    'Description': '',
    'Date sale price starts': '',
    'Date sale price ends': '',
    'Tax status': 'taxable',
    'Tax class': 'parent',
    'In stock?': '0',
    'Stock': '0',
    'Low stock amount': '',
    'Backorders allowed?': '0',
    'Sold individually?': '0',
    'Weight (lbs)': '',
    'Length (in)': '',
    'Width (in)': '',
    'Height (in)': '',
    'Allow customer reviews?': '0',
    'Purchase note': '',
    'Sale price': '0.00',
    'Regular price': '0.00',
    'Categories': '', # get category function
    'Tags': '', # get tag function
    'Shipping class': 'sng-1',
    'Images': '', # get image function
    'Download limit': '',
    'Download expiry days': '',
    'Parent': '', # find parent function
    'Grouped products': '',
    'Upsells': '',
    'Cross-sells': '',
    'External URL': '',
    'Button text': '',
    'Position': '', # find position function
    'Minimum Quantity': '',
    'Maximum Quantity': '',
    'Attribute 1 name': '',
    'Attribute 1 value(s)': '',
    'Attribute 1 visible': '',
    'Attribute 1 global': '',
    'Attribute 2 name': '',
    'Attribute 2 value(s)': '',
    'Attribute 2 visible': '',
    'Attribute 2 global': '',
    'Attribute 3 name': '',
    'Attribute 3 value(s)': '',
    'Attribute 3 visible': '',
    'Attribute 3 global': '',
    # 'Attribute 4 name': '',
    # 'Attribute 4 value(s)': '',
    # 'Attribute 4 visible': '',
    # 'Attribute 4 global': '',
    # 'Attribute 5 name': '',
    # 'Attribute 5 value(s)': '',
    # 'Attribute 5 visible': '',
    # 'Attribute 5 global': '',
    # 'Attribute 6 name': '',
    # 'Attribute 6 value(s)': '',
    # 'Attribute 6 visible': '',
    # 'Attribute 6 global': '',
}